# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: ⚙️ 配置帮助
description: 配置相关的问题或优化建议
title: "[配置] "
labels: ["配置", "帮助"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        遇到配置问题？我们来帮你解决！

        📖 **建议先查看 README 文档和配置文件注释**

  - type: dropdown
    id: config-type
    attributes:
      label: 🏷️ 配置类型
      options:
        - 基础配置问题
        - Webhook 配置
        - Docker 部署配置
        - 频率词配置
        - 平台配置
        - 定时任务配置
        - 其他
    validations:
      required: true

  - type: dropdown
    id: problem-type
    attributes:
      label: 🔍 问题类型
      options:
        - 配置不生效
        - 不知道如何配置
        - 配置优化建议
        - 配置文档改进
        - 配置验证问题
    validations:
      required: true

  - type: textarea
    id: config-content
    attributes:
      label: 📄 相关配置
      description: 请提供相关的配置内容（请隐藏敏感信息）
      placeholder: |
        请贴出相关的配置片段（记得隐藏敏感信息）：
        
        ```yaml
        notification:
          enable_notification: true
          webhooks:
            feishu_url: "***"
        ```
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 📝 问题描述
      description: 详细描述遇到的配置问题
      placeholder: |
        请详细描述：
        - 遇到的具体问题
        - 期望的效果
        - 已经尝试的方法
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: ❌ 错误信息（如果有）
      description: 相关的错误信息或日志
      placeholder: |
        如果有错误信息，请贴出来：
        
        ```
        错误信息...
        ```

  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ 运行环境
      options:
        - 本地 Python 环境
        - Docker 容器
        - GitHub Actions
        - 其他
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📎 其他信息
      description: 其他可能有用的信息
      placeholder: |
        - 操作系统版本
        - 网络环境
        - 使用场景
        - 其他相关信息